classDiagram

MinorCineflex o-- Cinema
MinorCineflex o-- Person
class MinorCineflex{
        -cinema_list: List[Cinema]
        -person_list: List[Person]
    }

Cinema --> CinemaManagement
class Cinema {
        -cinema_id: str
        -name: str
        -location: str
        -opentime: datetime
        -closetime: datetime
        -cinema_management: CinemaManagement
    }

CinemaManagement o-- Theater
CinemaManagement o-- Showtime
CinemaManagement o-- Booking
CinemaManagement o-- Movie
class CinemaManagement{
        -theater_list: List[Theater]
        -snack_list: List[Snack]
        -showtime_list: List[Showtime]
        -booking_list: List[Booking]
        -movie_list: List[Movie]
    }

Person <|-- User
Person <|-- Admin
Person --> Account
class Person {
        -name: str
        -tel_no: str
        -email: str
        -birthday: datetime
        -gender: str
        -account: Account
    }
class User {

    }
class Admin {

    }

Account o-- Booking
Account o-- Document
class Account {
        -username: str
        -password: str
        -account_id: str
        -point: int
        -registered_date: datetime
        -exiration_date: datetime
        -history: List[Booking]
        -document_list: List[Document]
    }   

class Movie {
        -name: str
        -type: str
        -movie_id: str
        -detail: str
        -duration: int
    }

Theater o-- Maintainance
Theater o-- SeatMap
class Theater {
        -theater_id: str
        -theater_type: str
        -seat_amount: int
        -status: bool
        -audio_type: str
        -video_type: str
        -maintainance_list: List[Maintainance]
    }

Showtime --> Cinema
Showtime --> Theater
Showtime --> Movie
class Showtime {
        -showtime_id: str
        -start_date: datetime
        -cinema: Cinema
        -theater: Theater
        -movie: Movie
        -dub: bool
        -sub: bool
        -available_seat: List[Seat]
        -reserved_seat: List[Seat]
    }

class Payment {
        -payment_type: str
    }

class SeatMap {
        -map_type: str
        -map: list_2d
    }

Seat <|-- DeluxeSeat
Seat <|-- PremiumSeat
Seat <|-- HoneymoonSeat
Seat <|-- FirstClass
Seat <|-- IMAXSeat
class Seat {
        -seat_id: str
        -seat_type: str
        -size: int
        -price: float
    }
class DeluxeSeat {

    }
class PremiumSeat {

    }
class HoneymoonSeat {

    }
class FirstClass {

    }
class IMAXSeat {

    }


class Maintainance {
        -detail: str
        -start_date: datetime
        -end_date: datetime
    }

Booking o-- Seat
Booking --> Payment
Booking --> Showtime
class Booking {
        -showtime: Showtime
        -account_id: str
        -seat_list: List[Seat]
        -booking_date: datetime
        -payment_method: Payment
        -total: float
    } 

Document --> Booking
class Document {
        -booking: Booking
        -document_type: str
    }
